# Generated by Django 2.2.3 on 2019-07-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
