# Generated by Django 2.2.3 on 2019-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_resource', '0002_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
