# Generated by Django 2.2.3 on 2019-08-12 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_resource', '0003_auto_20190812_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
