# Generated by Django 2.2.3 on 2019-08-03 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_resource', '0006_auto_20190803_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona'},
        ),
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procedure_resource.DocumentType', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Enlace de descarga'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='identificación'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='primer apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='person',
            name='procedures',
            field=models.ManyToManyField(through='procedure_resource.PersonProcedure', to='procedure_resource.Procedure', verbose_name='trámites'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo apellido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='segundo nombre'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizdo el'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.TextField(verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure_resource.Departament', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='esta activo'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='position',
            field=models.SmallIntegerField(verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure_resource.Procedure', verbose_name='trámite'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='requirements',
            field=models.ManyToManyField(to='procedure_resource.DocumentType', verbose_name='requisitos'),
        ),
    ]
