# Generated by Django 2.2.3 on 2019-08-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure_resource', '0009_auto_20190805_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
