# Generated by Django 2.2.3 on 2019-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='direccion',
        ),
        migrations.AddField(
            model_name='rent',
            name='adress',
            field=models.CharField(default='', max_length=255, verbose_name='adress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
    ]
